require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
Style/Documentation:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "config/environments/development.rb"
