name: Deploy

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test-action.yml

  deploy:
    name: Deploy to dokku
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@dokku.wells.tw:22/charity-web'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_push_flags: --force -vvv

      - name: Run database migration
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: dokku.wells.tw
          username: dokku
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: run charity-web rails db:migrate